function a = iscover(LON,LAT,T_LON,T_LAT)

a=T_LAT(1)<= max(LAT(1),LAT(2)) && T_LAT(1)>= min(LAT(3),LAT(4)) &&...
    T_LAT(2)<= max(LAT(1),LAT(2)) && T_LAT(2)>= min(LAT(3),LAT(4)) &&...
    T_LON(1)<= max(LON(2),LON(4)) && T_LON(1)>= min(LON(1),LON(3))&&...
    T_LON(2)<= max(LON(2),LON(4)) && T_LON(2)>= min(LON(1),LON(3));